"""Add title and date columns to pitches

Revision ID: 4c2029128345
Revises: 75e76abf6d7c
Create Date: 2019-05-27 07:28:46.437025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2029128345'
down_revision = '75e76abf6d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'posted')
    # ### end Alembic commands ###
