"""Add postedBy Column to Comments

Revision ID: 5768ffdf65d2
Revises: 94ffcec4f5f9
Create Date: 2019-05-28 04:42:27.386842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5768ffdf65d2'
down_revision = '94ffcec4f5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted_by')
    # ### end Alembic commands ###
