"""Modify relationship between user and pitches

Revision ID: 75e76abf6d7c
Revises: ca3a7ef77c7e
Create Date: 2019-05-27 04:57:27.727909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e76abf6d7c'
down_revision = 'ca3a7ef77c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'comments', ['user_id'], ['id'])
    # ### end Alembic commands ###
