"""Add postedBy column to Pitch table

Revision ID: 94ffcec4f5f9
Revises: 4c2029128345
Create Date: 2019-05-28 03:13:04.351137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ffcec4f5f9'
down_revision = '4c2029128345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'posted_by')
    # ### end Alembic commands ###
